server:
  port: 8080
  undertow:
    io-threads: 8
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 128

spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/flink_hlink?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #邮件发射账户配置
  mail:
    username: xxxx@163.com
    #填写授权码
    password: xxxxxxx
    #填写邮箱供应的SMTP地址
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 500MB  #上传单个文件的大小
      max-request-size: 50GB  #上传文件的总大小
      file-size-threshold: 10KB #文件上传临界值，超过这个临界值，保存到location
      location: /Users/leon/Documents/items/test/tmp #文件上传临时保存目录
  devtools:
    restart:
      enabled: false  #设置开启热部署
  # redis配置
  redis:
    host: 127.0.0.1  # IP
    port: 6379  # 端口号
    password: 123456  # 密码
    timeout: 10000
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接

#flink 相关配置
flink:
  client:
    dir: /Users/leon/Documents/items/server/flink-1.9.2
  shell:
    # 设置sql作业的提交数据方式，默认ds，即连接数据库。备用方式file，文件.
    datamode: ds
    # 设置用于sql作业的提交Jar包路径.
    jarpath: /Users/leon/Documents/items/ideaprojects/hlink/sql-submit/target/flink-sql-submit.jar
  udf:
    # 设置默认的UDF上传路径,共享目录.
    location: /Users/leon/Documents/items/test/udf
  # 设置Flink rest连接相关参数.
  rest:
    connectTimeOut: 20000
    writeTimeOut: 30000
    readTimeOut: 30000
    debug: false


debug: false

#启用所有的监控端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#swagger API 开关
swagger:
  enable: false
#配置此属性为true后,所有资源都会屏蔽输出.
knife4j:
  production: true
# javamelody数据监控
javamelody:
  # 禁用JavaMelody自动配置
  enabled: false
